name: 'dbt_sql_optimisations_examples'
version: '1.0.0'
config-version: 2

profile: 'dbt_sql_optimisations_examples'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "{{ env_var('DBT_TARGET_PATH') }}"
  - "{{ env_var('DBT_PACKAGE_PATH') }}"

models:
  dbt_sql_optimisations_examples:
    silver:
      +database: "{{ env_var('DBT_SILVER_DATABASE') }}"
      +schema: "{{ env_var('DBT_SILVER_SCHEMA') }}"
      +materialized: view

    gold:
      +database: "{{ env_var('DBT_GOLD_DATABASE') }}"
      +schema: "{{ env_var('DBT_GOLD_SCHEMA') }}"
      +materialized: table
      +transient: false
